---
- hosts: all

  vars_files:
    - ../config.yml

  pre_tasks:
    - include: tasks/init-debian.yml
      when: ansible_os_family == 'Debian'
    - include: tasks/init-redhat.yml
      when: ansible_os_family == 'RedHat'

  roles:
    # Essential roles.
    - { role: geerlingguy.repo-remi, when: ansible_os_family == 'RedHat' }
    - geerlingguy.firewall
    - geerlingguy.git
    - geerlingguy.apache
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.composer
    - geerlingguy.drush
    - { role: geerlingguy.drupal-console, when: drupal_major_version > 7 }

    # Conditionally-installed roles.
    - { role: geerlingguy.memcached, when: '"memcached" in installed_extras' }
    - { role: geerlingguy.php-memcached, when: '"memcached" in installed_extras' }
    - { role: geerlingguy.php-xdebug, when: '"xdebug" in installed_extras' }
    - { role: geerlingguy.php-xhprof, when: '"xhprof" in installed_extras' }
    - { role: geerlingguy.adminer, when: '"adminer" in installed_extras' }
    - { role: geerlingguy.pimpmylog, when: '"pimpmylog" in installed_extras' }
    - { role: geerlingguy.daemonize, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.mailhog, when: '"mailhog" in installed_extras' }
    - { role: geerlingguy.java, when: '"solr" or "selenium" in installed_extras' }
    - { role: arknoll.selenium, when: '"selenium" in installed_extras' }
    - { role: geerlingguy.solr, when: '"solr" in installed_extras' }
    - { role: geerlingguy.varnish, when: '"varnish" in installed_extras' }
    - { role: Stouts.jenkins, develop, sudo: yes, when: '"jenkins" in installed_extras' }

    # Roles for security and stability on production.
    - { role: geerlingguy.security, when: extra_security_enabled }

  tasks:
    - name: Check if Drupal is already set up.
      stat: "path={{ drupal_core_path }}/index.php"
      register: drupal_site

    - include: tasks/extras.yml
    - include: tasks/www.yml
    - include: tasks/apparmor.yml
      when: ansible_os_family == 'Debian'

    # Build makefile if configured.
    - include: tasks/build-makefile.yml
      when: build_makefile and not acquia_cloud_connector

    # Install site if configured.
    - include: tasks/install-site.yml
      when: install_site and not import_site and not acquia_cloud_connector

    # Import site if configured.
    - include: tasks/import-site.yml
      when: import_site and not install_site and not acquia_cloud_connector

    # Deploy theme if configured.
    - include: tasks/deploy-theme.yml
      when: drupal_theme_repository is defined and not acquia_cloud_connector

    # Use Acquia Cloud to deploy if configured.
    - include: tasks/acquia-cloud.yml
      environment:
        ACQUIA_CLOUD_USERNAME: "{{ acquia_cloud_username }}"
        ACQUIA_CLOUD_PASSWORD: "{{ acquia_cloud_password }}"
        ACQUIA_CLOUD_SITE_ID: "{{ acquia_cloud_sitename }}"
        ACQUIA_CLOUD_ENVIRONMENT: "{{ acquia_cloud_environment }}"
      when: acquia_cloud_connector

    - include: tasks/drush-aliases.yml
    - include: tasks/drush-stage-file-proxy.yml
    - include: tasks/drush-shield.yml
    - include: tasks/cron.yml
    - include: tasks/jenkins.yml
